//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<zBuilding> zBuilding { get; set; }
        public DbSet<zDay> zDay { get; set; }
        public DbSet<zDepartment> zDepartment { get; set; }
        public DbSet<zFacility> zFacility { get; set; }
        public DbSet<zLecturer> zLecturer { get; set; }
        public DbSet<zModule> zModule { get; set; }
        public DbSet<zPark> zPark { get; set; }
        public DbSet<zPeriod> zPeriod { get; set; }
        public DbSet<zPreference> zPreference { get; set; }
        public DbSet<zProgramme> zProgramme { get; set; }
        public DbSet<zRequest> zRequest { get; set; }
        public DbSet<zRoom> zRoom { get; set; }
        public DbSet<zRound> zRound { get; set; }
        public DbSet<zStatus> zStatus { get; set; }
        public DbSet<zUser> zUser { get; set; }
        public DbSet<zWeek> zWeek { get; set; }

        public DbSet<TeamProject.zFacility> zFacilities { get; set; }

        public DbSet<TeamProject.zRoom> zRooms { get; set; }

        public DbSet<TeamProject.zRound> zRounds { get; set; }
    }
}
