//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class zFacility
    {
        public zFacility()
        {
            this.zRequest = new HashSet<zRequest>();
            this.zRoom = new HashSet<zRoom>();
        }
    
        [Key]
        public short FacilityId { get; set; }
        public string FacilityName { get; set; }
    
        public virtual ICollection<zRequest> zRequest { get; set; }
        public virtual ICollection<zRoom> zRoom { get; set; }
    }
}
