//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class zLecturer
    {
        public zLecturer()
        {
            this.zModule = new HashSet<zModule>();
        }
        [Key]
        public int LecturerId { get; set; }
        public string LecturerName { get; set; }
    
        public virtual ICollection<zModule> zModule { get; set; }
    }
}
