//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class zPark
    {
        public zPark()
        {
            this.zBuilding = new HashSet<zBuilding>();
        }
    
        public short ParkId { get; set; }
        public string ParkName { get; set; }
    
        public virtual ICollection<zBuilding> zBuilding { get; set; }
    }
}
