//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class zPeriod
    {
        public zPeriod()
        {
            this.zRequest = new HashSet<zRequest>();
        }
    
        public short PeriodId { get; set; }
        public string PeriodValue { get; set; }
    
        public virtual ICollection<zRequest> zRequest { get; set; }
    }
}
