//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class zProgramme
    {
        public zProgramme()
        {
            this.zModule = new HashSet<zModule>();
        }
        [Key]
        public string ProgrammeCode { get; set; }
        public string ProgrammeTitle { get; set; }
        public string DeptCode { get; set; }
    
        public virtual zDepartment zDepartment { get; set; }
        public virtual ICollection<zModule> zModule { get; set; }
    }
}
