//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class zRoom
    {
        public zRoom()
        {
            this.zFacility = new HashSet<zFacility>();
            this.zDepartment = new HashSet<zDepartment>();
            this.zRequest = new HashSet<zRequest>();
        }
    
        public int RoomId { get; set; }
        public string RoomCode { get; set; }
        public int Capacity { get; set; }
        public string BuildingCode { get; set; }
        public string ImgLink { get; set; }
        public bool Private { get; set; }
    
        public virtual zBuilding zBuilding { get; set; }
        public virtual ICollection<zFacility> zFacility { get; set; }
        public virtual ICollection<zDepartment> zDepartment { get; set; }
        public virtual ICollection<zRequest> zRequest { get; set; }
    }
}
