//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class zStatus
    {
        public zStatus()
        {
            this.zRequest = new HashSet<zRequest>();
        }
    
        public short StatusId { get; set; }
        public string StatusValue { get; set; }
    
        public virtual ICollection<zRequest> zRequest { get; set; }
    }
}
