//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class zWeek
    {
        public zWeek()
        {
            this.zRequest = new HashSet<zRequest>();
        }
    
        public int WeekId { get; set; }
        public bool Week1 { get; set; }
        public bool Week2 { get; set; }
        public bool Week3 { get; set; }
        public bool Week4 { get; set; }
        public bool Week5 { get; set; }
        public bool Week6 { get; set; }
        public bool Week7 { get; set; }
        public bool Week8 { get; set; }
        public bool Week9 { get; set; }
        public bool Week10 { get; set; }
        public bool Week11 { get; set; }
        public bool Week12 { get; set; }
        public bool Week13 { get; set; }
        public bool Week14 { get; set; }
        public bool Week15 { get; set; }
        public bool Week16 { get; set; }
    
        public virtual ICollection<zRequest> zRequest { get; set; }
    }
}
