//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TeamProject2
{
    public partial class zDepartment
    {
        public zDepartment()
        {
            this.zModule = new HashSet<zModule>();
            this.zProgramme = new HashSet<zProgramme>();
            this.zUser = new HashSet<zUser>();
            this.zRoom = new HashSet<zRoom>();
        }
    
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<zModule> zModule { get; set; }
        public virtual ICollection<zProgramme> zProgramme { get; set; }
        public virtual ICollection<zUser> zUser { get; set; }
        public virtual ICollection<zRoom> zRoom { get; set; }
    }
    
}
