//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TeamProject2
{
    public partial class zLecturer
    {
        public zLecturer()
        {
            this.zModule = new HashSet<zModule>();
        }
    
        public int LecturerId { get; set; }
        public string LecturerName { get; set; }
        public string DeptCode { get; set; }
    
        public virtual zDepartment zDepartment { get; set; }
        public virtual ICollection<zModule> zModule { get; set; }
    }
    
}
