//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TeamProject2
{
    public partial class zModule
    {
        public zModule()
        {
            this.zRequest = new HashSet<zRequest>();
            this.zLecturer = new HashSet<zLecturer>();
            this.zProgramme = new HashSet<zProgramme>();
        }
    
        public string ModCode { get; set; }
        public string ModTitle { get; set; }
        public string DeptCode { get; set; }
        public string Part { get; set; }
    
        public virtual zDepartment zDepartment { get; set; }
        public virtual ICollection<zRequest> zRequest { get; set; }
        public virtual ICollection<zLecturer> zLecturer { get; set; }
        public virtual ICollection<zProgramme> zProgramme { get; set; }
    }
    
}
