//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TeamProject2
{
    public partial class zProgramme
    {
        public zProgramme()
        {
            this.zModule = new HashSet<zModule>();
        }
    
        public int ProgrammeCode { get; set; }
        public string ProgrammeTitle { get; set; }
        public string DeptCode { get; set; }
        public string Part { get; set; }
        public bool GradType { get; set; }
        public bool ProgramType { get; set; }
    
        public virtual zDepartment zDepartment { get; set; }
        public virtual ICollection<zModule> zModule { get; set; }
    }
    
}
