//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TeamProject2
{
    public partial class zRoom
    {
        public zRoom()
        {
            this.zRoomBooking = new HashSet<zRoomBooking>();
            this.zRequest = new HashSet<zRequest>();
            this.zFacility = new HashSet<zFacility>();
            this.zDepartment = new HashSet<zDepartment>();
        }
    
        public int RoomId { get; set; }
        public string RoomCode { get; set; }
        public int Capacity { get; set; }
        public string ImgLink { get; set; }
        public bool Private { get; set; }
        public int BuildingId { get; set; }
    
        public virtual zBuilding zBuilding { get; set; }
        public virtual ICollection<zRoomBooking> zRoomBooking { get; set; }
        public virtual ICollection<zRequest> zRequest { get; set; }
        public virtual ICollection<zFacility> zFacility { get; set; }
        public virtual ICollection<zDepartment> zDepartment { get; set; }
    }
    
}
